FORMAT: 1A
HOST: http://heartcup.apiblueprint.org/

# HeartCup API

## Users [/users]

### Get User [GET /user/{user}]

Fetch the user details

+ Parameters
    + user (required) - The user ID or email address

+ Response 200 (application/json)
    - Attributes (StoredUser)
    
+ Response 404 (application/json)
    - Attributes
        - message: User does not exist (string) - The error message

### Following [GET /user/{user}/following/{type}]

Fetch all users, projects, or organizations that the given user follows. Returns
an array of stored objects of the specified type.

+ Parameters
    + user (required) - The user ID or email address
    + type (required, number) - The type of object the user is following (1 - User, 2 - Project, 3 - Organization)

+ Response 200 (application/json)
    - Attributes (array[object])

+ Response 404 (application/json)
    - Attributes
        - message: User not found (string) - The error message
        
+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: Failed to create project (string) - The error message


### Follow [POST /user/{user}/following/{type}/{id_to_follow}]

Add entity of the specified type to the given user's following list 

+ Parameters
    + user (required) - The user ID or email address
    + type (required, number) - The type of object being followed (1 - User, 2 - Project, 3 - Organization)
    + id_to_follow (required) - The ID of the object being followed

+ Response 204 (application/json)

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message
        
+ Response 404 (application/json)
    - Attributes
        - message: Entity not found (string) - The error message

+ Response 422 (application/json)
    - Attributes
        - message: Error following entity (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: Failed to create project (string) - The error message

### Unfollow [DELETE /user/{user}/following/{type}/{id_to_unfollow}]

Remove entity of the specified type from the given user's following list

+ Parameters
    + user (required) - The user ID or email address
    + type (required, number) - The type of object to remove (1 - User, 2 - Project, 3 - Organization)
    + id_to_unfollow(required) - The ID of the object being removed

+ Response 204 (application/json)

+ Response 404 (application/json)
    - Attributes
        - message: Entity not found (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

### Login [POST /user/token]

Create a JWT token for the given user

+ Attributes
    + emailAddress (required) - The user's email address
    + password (required) - The user's password

+ Response 200 (application/json)
    - Attributes
        - token: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ` (string) - The JWT Token

+ Response 403 (application/json)
    - Attributes
        - message: Invalid email address or password (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: Authentication Failed (string) - The error message

### Logout [POST /user/logout]

Invalidate the given user's JWT token

+ Response 204 (application/json)

+ Response 403 (application/json)
    - Attributes
        - message: Unauthorized request (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: Authentication Failed (string) - The error message

### Register [POST /user]

Register a new user

+ Attributes (User)
    + password (required) - The user's password

+ Request (application/x-www-form-urlencoded)
    
+ Response 201 (application/json)
    - Attributes (User)

+ Response 422 (application/json)
    - Attributes
        - message: User already exists (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: Failed to create user (string) - The error message

### Update [PUT /user/{user}]

Update the given user

+ Parameters
    + user (required) - The user ID or email address

+ Attributes (User)

+ Response 204 (application/json)

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: Failed to create project (string) - The error message

### Update Profile Image [PUT /user/{user}/profileImage]

Update the given user's profile image

+ Parameters
    + user (required) - The user ID or email address

+ Response 204 (application/json)

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

## Projects [/project]

### Search [GET /project{?query,orderBy,order,limit,page}]

Search for projects. Returns a list of project summaries.

+ Parameters
    + query (optional) - Search query
    + orderBy (optional) - Project attribute to order by
    + order (optional) - DESC or ASC (default: DESC)
    + limit (optional) - The maximum number of projects to return
    + page (optional) - The page to return, if limit is also given

+ Response 200 (application/json)
    - Attributes (object)
        - total (number)
        - per_page (number) 
        - current_page (number)
        - last_page (number)
        - next_page_url (string)
        - prev_page_url (string)
        - from (number) 
        - to (number) 
        - data (array)
            - (Project)
                - id: 1 (number)
                - title: After School Programs
            - (Project)
                - id: 2 (number)
                - title: Music in the Park
            - (Project)
                - id: 3 (number)
                - title: Local Animal Shelter

### Project Detail [GET /project/{projectId}]

Fetch the details of a project. Takes the project ID or key as a parameter

+ Parameters
    + projectId (required, string) - The Project ID or Key

+ Response 200 (application/json)
    - Attributes (ProjectDetail)

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

### Supporters [GET /project/{projectId}/supporters]

Fetch an array of supporters for a project. Takes the project ID or key as a parameter.

+ Parameters
    + projectId (required, string) - The Project ID or Key
    
+ Response 200 (application/json)
    - Attributes (array[StoredUser])

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

### Create Project [POST /project]

Create a new project.

+ Request (application/x-www-form-urlencoded)
    + Attributes
        + title: New Project Title (required, string) - The title of the new project
        + tagline (optional, string)
        + summary (optional, string)
        + goalAmount (optional, number)
        + goalDate (string) - The target date for this project to be completely funded (ISO8601 format)
        + ownerType (optional,number) - The type of entity that owns the project (user/organzation).  If not specified API uses authenticated user.
        + ownerEntityId (optional,number) - The entity id of the object that owns the project. If not specified API uses authenticated user.

+ Response 201 (application/json)
    - Attributes (Project)

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: Failed to create project (string) - The error message

### Update a Project [PUT /project/{projectId}]

Update a project.

+ Parameters
    + projectId: 1 (required, number) - The ID of the project to update.

+ Request (application/x-www-form-urlencoded)
    + Attributes
        + title: New Project Title (required, string) - The title of the new project
        + tagline (optional, string)
        + summary (optional, string)
        + goalAmount (optional, number)
        + goalDate (string) - The target date for this project to be completely funded (ISO8601 format)

+ Response 204 (application/json)

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message
        
+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

### Delete a Project [DELETE /project/{projectId}]

Delete a project

+ Parameters
    + projectId (required, number) - The ID of the project to delete

+ Response 204 (application/json)

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

## Search [/search]

### Search [GET /search/{?query,type,orderBy,order,limit,page}]

Produce a search for Users or Projects

+ Parameters
    + query (optional) - Search query
    + type (optional) - The type of object to search for (Project or User)
    + orderBy (optional) - Attribute to order by
    + order (optional) - DESC or ASC (default: DESC)
    + limit (optional) - The maximum number to return
    + page (optional) - The page to return, if limit is also given

+ Response 200 (application/json)
    - Attributes (array)
        - (Project)
            - id: 1 (number)
            - title: After School Programs
        - (User)
        - (Project)
            - id: 3 (number)
            - title: Local Animal Shelter

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

## Categories [/category]

### Get all Categories [GET /category]

Fetch all categories

+ Response 200 (application/json)
    + Attributes (array[Category])

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred
### Browse Category [GET /category/{?category_key,orderBy,order,limit,page}]

List everything in a given category

+ Parameters
    + category_key (optional) - The key for the category
    + orderBy (optional) - Attribute to order by
    + order (optional) - DESC or ASC (default: DESC)
    + limit (optional) - The maximum number to return
    + page (optional) - The page to return, if limit is also given

+ Response 200 (application/json)
    - Attributes (array[StoredCategory])

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

### Update Category [PUT /category/{category}]

Update a given category

+ Parameters
    + category (required) - The ID or key for the category to update

+ Response 204 (application/json)
    + Attributes (Category)

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

### Create Category [POST /category]

Create a new category

+ Response 201 (application/json)

+ Response 422 (application/json)
    + Attributes
        - message: Category already exists (string) - The error message

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

### Delete Category [DELETE /category/{category}]

Delete the given category

+ Parameters 
    + category (required) - The ID or key for the category to remove

+ Response 204 (application/json)

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

## Transactions [/paygate]

### View Transaction [GET /paygate/{transaction}]

Fetch details for a transaction

+ Parameters
    + transaction (required) - The ID of the transaction

+ Response 200 (application/json)
    + Attributes (Transaction)

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

### View Donation [GET /paygate/donate/{donation}]

Fetch the donation record

+ Parameters
    + donation (required) - The ID of the donation

+ Response 200 (application/json)
    + Attributes (Donation)

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

### Update Transaction [PUT /paygate/{transaction}]

Update the given transaction

+ Parameters
    + transaction (required) - The ID of the transaction to update

+ Response 200 (application/json)
    + Attributes (Transaction)

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

### Update Donation [PUT /paygate/donate/{donation}]

Update the given donation

+ Parameters 
    + donation (required) - The ID of the donation to update

+ Response 200 (application/json)
    + Attributes (Donation)

+ Response 204 (application/json)

### Buy Hearts [POST /paygate]

Purchase Hearts

+ Response 200 (application/json)
    + Attributes (Transaction)

+ Response 400 (application/json)

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

### Donate [POST /paygate/donate/{donation}]

Donate to a project

+ Parameters
    + donation (required) - Project ID to submit donation to

+ Response 200 (application/json)
    + Attributes (Donation)

+ Response 400 (application/json)

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

## Organizations [/organization]

### Get All Organizations [GET /organization]

Fetch all organizations

+ Response 200 (application/json)
    + Attributes (array[Organization])

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred (string) - The error message

### Get Organization [GET /organization/{organization}]

Fetch the given organization

+ Parameters 
    + organization (required) - The ID or key of the organization to retrieve

+ Response 200 (application/json)
    + Attributes (Organization)

+ Response 404 (application/json)
    + Attributes
        - message: Organization not found (string) - The error message
        
+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred (string) - The error message

### Update Organization [PUT /organization/{organization}]

Update the given organization

+ Parameters
    + organization (required) - The ID or key of the organization to update

+ Response 204 (application/json)

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 404 (application/json)
    - Attributes
        - message: Organization not found (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred (string) - The error message

### Create Organization [POST /organization]

Create a new organization

+ Response 201 (application/json)
    + Attributes (Organization)

+ Response 401 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 422 (application/json)
    + Attributes
        + message: Organization already exists (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred (string) - The error message

### Delete Organization [DELETE /organization/{organization}]

Soft delete specified organization

+ Response 200 (application/json)
    -  Attributes
        - message: Organization was successfully deleted (string) - The response message

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message
        
+ Response 404 (application/json)
    - Attributes
        - message: Organization not found (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred (string) - The error message

## Update [/update]

### Get Post [GET /update/{id}]

Get a post for a given entity (User, Project, Organization)

+ Parameters 
    + id - The ID or key for the given entity 

+ Response 200 (application/json)
    + Attributes (Update)

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

### Get Posts By Entity [GET /update/{type}/{entity_id}]

Get posts for the given entity

+ Parameters
    + type - The update type (1 - User, 2 - Project, 3 - Organization)
    + entity_id - The ID of the entity

+ Response 200 (application/json)
    + Attributes (array[Update]) 

+ Response 400 (application/json)
    - Attributes
        - message: Invalid request (string) - The error message
        
+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

### Create Post [POST /update]

Create a new post

+ Response 201 (application/json)
    + Attributes (Update)

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500
    - Attributes
        - message: An error has occurred

### Update Post [PUT /update/{update}]

Update the given activity

+ Parameters
    + update - The given activity ID

+ Response 200 (application/json)

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500
    - Attributes
        - message: An error has occurred

### Delete Post [DELETE /update/{update}]

Delete the given activity

+ Parameters
    + update - The given update ID 

+ Response 200

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500
    - Attributes
        - message: An error has occurred

## MessageQueue [/messages]

### Get Messages [GET /messages/{user}]

Get the messages for the given user

+ Parameters 
    + user - The ID or key of the given user

+ Response 200 (application/json)

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

### Create Message [POST /messages/{type}]

Add a given type of message to the queue

+ Parameters
    + type - The type of activity (ProfileUpdate or ProjectUpdate)

+ Response 201 (application/json)
    - Attributes
        - message: Message has been created.

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

### Delete Message [DELETE /messages/{id}]

Delete a message from the queue when received

+ Parameters
    + id - ID of the message to delete

+ Response 200 (application/json)

+ Response 403 (application/json)
    - Attributes
        - message: Permission denied (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

## Contact [/contact]

### Contact Form [POST /contact]

Send a message through the contact form

+ Response 200 (application/json)
    + Attributes 
        + message: Your message has been received and will be reviewed shortly (string) - The verification message

+ Response 400 (application/json)
    + Attributes 
        + message: Fields cannot be left blank (string) - The error message

+ Response 500 (application/json)
    - Attributes
        - message: An error has occurred

# Data Structures

## User

+ email: `user@example.com` (string) - The user's email address
+ profileImage (Image) - The user's profile image
+ name: Sample User (string) - The user's display name
+ accountType (enum[string]) - The user's account type
    + Default: regular
    + Members
        + regular (default) - Regular user
        + pro - Pro user (paid account)
+ privacy (object) - The user's privacy settings
    + profile (enum[string]) - The user's profile visibility
        + Default : public
        + Members
            + hidden - The user's profile is hidden
            + public (default) - The user's profile is visible to anyone, links to the user's profile may appear on HeartCup
            + link - The user's profile is only visible with a direct link
    + donations (enum[string]) - The user's donation visibility
        + Default: projects
        + Members
            + hidden - Do not show projects supported or donation amounts
            + projects (default) - Only show projects the user supports
            + public - Show projects and donation amounts
+ followingUsers (array[StoredUser]) - The users that the given user follows
+ followingProjects (array[StoredProject]) - The projects that the given user follows
+ followingOrganizations (array[Organization]) - The organizations that the given user follows
+ paymentMethod (object) - Object representing the user's payment card
+ ownedProjects (array[StoredProject]) - Array representing projects created and owned by the user
+ school (School) - The user's associated school
+ coreValues: `Core Value 1, Core Value 2, Core Value 3` (string) - The user's core value preferences
+ organizations (array[Organization]) - The organizations that the given user is a member of
+ newsletterOptIn (enum[number]) - User's opt-in option for the newsletter
    + Default: 1
    + Members
        + 0 - Opt-Out / Disabled
        + 1 (default) - Opt-In / Enabled

### StoredUser (User)

+ id: 1 (number) - The user ID
+ posts (array[ProfileUpdate]) - Array of user's profile activity
+ accountBalance: 100.00 (number) - The user's account balance (in hearts?)
+ backers (array[StoredUser]) - Array of user IDs of people who support the given user's owned projects
+ totalDonated: 100.00 (number) - Aggregated amount representing how much the user has donated to various projects
+ totalReceived: 100.00 (number) - Aggregated amount representing how much the user has received in support for owned projects
+ isActive (enum[number]) - Value representing whether or not the user account is still active
    + Default: 1
    + Members
        + 0 - Inactive / Disabled
        + 1 (default) - Active/ Enabled

## Project

+ title: The Outreach Project (string) - The project title
+ tagline: Sponsored by the Giving Keys (string) - The project tagline
+ thumbnail (Image) - The project thumbnail
+ banner (Image) - The project banner
+ address (Address) - The project address
+ organizationId: 1 (number) - The id of the organization that owns this project
+ summary: Sample Project Summary (string) - The project summary
+ goalAmount: 10000 (number) - The project goal amount in hearts
+ goalDate: `2016-05-05T12:30:00` (string) - The target date for this project to be completely funded (ISO8601 format)
+ owner (object) - The user or organization that owns the project

### StoredProject (Project)

+ id: 55 (number) - The project ID
+ key: 1 (number) - The ID of the URL key corresponding to the project
+ fundedAmount: 500 (number) - The total funds collected for the project in hearts (integer)
+ supportersTotal: 65 (number) - The total number of supporters for this project

#### ProjectDetail (StoredProject)

+ description: Basic Project Description (string) - Description of the project
+ details (object) - Details of the project
+ supporters (array[StoredUser]) - Array representing users who support this project
+ currency (enum[string]) - The type of currency expected for the project (USD default)
    + Default: USD
    + Members
        + USD (default)
+ taxExemptStatus (enum[number]) - The projects tax exemption status
    + Default: 0
    + Members
        + 0 (default) - Non Charitable Project - For Profit
        + 1 - Chartiable Project - Non Profit
+ approved (enum[string]) - Value representing the approval status of the project
    + Default: 0
    + Members
        + 0 (default) - Pending Approval
        + 1 - Project Approved
        + 2 - Project Disapproved
+ active (enum[string]) - Value representing the state of the project, whether it is active or not
    + Default: 1
    + Members
        + 0 - Inactive / Disabled
        + 1 (default) - Active
+ categories (array[StoredCategory]) - The categories associated with this project
+ posts (array[ProjectUpdate]) - The status updates associated with the given project

## Address

+ id: 1 (number) - The address ID
+ line1: 123 Someplace Nice (string) - Address line 1
+ line2 (string) - Address line 2
+ locality: Sunny (string) - The address locality or city
+ region: CA (string) - The address region, state or province
+ postcode: 90210 (string) - The address postcode
+ countryCode: USA (string) - The address country code

## Image
+ id: 1 (number) - The image ID
+ width: 150 (number) - The image width
+ height: 150 (number) - The image height
+ url: `http://lorempixel.com/800/600/cats/` (string) - The image URL
+ alt_text (string) - The alternate text for the image.
+ position (number) - The sort order for multiple images.
+ createdAt (string) - The image creation date (ISO8601 format)
+ updatedAt (string) - The image creation date (ISO8601 format)

## UrlKey

+ id: 1 (number) - The UrlKey ID
+ key: `the-url-key` (string) - Hashed string representing the url
+ type (enum[number]) - The INT value corresponding to the type of entity to which this key belong
    + Default: 0
    + Members
        + 0 (default) - Project
        + 1 - Organization
+ entityId: 1 (number) - The ID of the object to which this key belong (StoredProject.id, etc)

## Update

+ id: 1 (number) - The update ID
+ entityId: 1 (optional, number) - Optional ID of related entity
+ type (enum[number]) - The type of status update - project update, profile post
    + Default: 0
    + Members
        + 0 - ProfileUpdate - Profile Post
        + 1 - ProjectUpdate - Project Update
+ description: Dummy Post Content (string) - The update description
+ createdDate: `2016-05-05T12:30:00` (string) - The update date (ISO8601 format)
+ status: 1 (enum[number]) - Pending Moderation / Approved / Denied / Inactive (Disabled)


### ProjectUpdate (Update)

+ projectId: 1 (number) - The project ID associated with the status update
+ userId: 1 (number) - The ID of the user who created the status update

### ProfileUpdate (Update) 

+ userId: 1 (number) - The user ID associated with the status update
+ organizationId: 1 (number) - The organization ID associated with the status update

## Transaction

+ id: 1 (number) - The project ID associated with the transaction
+ userId: 1 (number) - The ID of the user who created the transaction
+ type (enum[number]) - Donation / Payment
    + Default: 1
    + Members
        + 0 - Donation
        + 1 (default) - Payment
+ timestamps (string) - The transaction date (ISO8601 format)
+ details (object) - Transaction receipt

### Donation(Transaction)

+ projectId: 1 (number) - The project ID associated with the donation

## Permission

+ roleId: 1 (number) - The ID of the type of role 
+ resourceAction (enum[string]) - The action which needs permission
    + Members
        + update
        + delete
+ permission (enum[string]) - The grant or deny permission for the action
    + Members
        + 1
        + 0
+ created_at (string) - The transaction date (ISO8601 format)
+ updated_at (string) - The transaction date (ISO8601 format)

## Role

+ id: 1 (number) - The ID for the role
+ title (enum[string]) - The title of the role
    + Default: member
    + Members
        + owner - Project/Organization Owner
        + moderator - Can post/approve content for project/organization.
        + editor - Can post content for project/organization to moderation queue.
        + member (default) - Can view project/organization.

## Category

+ name: Sample Category (string) - The name of the category

### StoredCategory(Category)

+ id: 1 (number) - The ID of the stored category
+ key: 1 (number) - The ID of the URL key corresponding to the category

## Organization

+ id: 1 (number) - The organization ID
+ title: Sample Organization (string) - The title of the organization
+ key: 1 (number) - The ID of the URL key corresponding to the organization
+ type: 1 (number) - Charity / Business / Group / Etc
+ members (array[OrganizationMember]) - An array of organization members
+ owner (object) - The organization owner
+ posts (array[ProfileUpdate]) - The status updates associated with the given project

### School (Organization)

### Charity (Organization)

+ taxEIN: `00-0000000` (string) - The tax employer identification number for charitable organization

## OrganizationMember

+ id: 1 (number) - The ID of the organization member
+ organizationId: 1 (number) - The ID of the organization that the member is a part of
+ userId: 1 (number) - The ID of the stored user 